import type { Metadata } from 'next';
import { Vazirmatn } from 'next/font/google';
import './globals.css';
import Header from '@/components/layout/Header';

const vazirmatn = Vazirmatn({
  variable: '--font-Vazirmatn',
  subsets: ['arabic'],
});

export const metadata: Metadata = {
  title: 'فروشگاه دیجی شاپ',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${vazirmatn.variable} antialiased`}>
        <Header />
        <main className="container  mx-auto px-5 mt-20">{children}</main>
      </body>
    </html>
  );
}
